#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box bootloader"
  echo
}

main() {
  banner

  bot "Place your device in FASTBOOT MODE!"
  warn "Power off your device"
  warn "Power on device while holding volume down"
  read -rp "Press enter to continue"

  bot "Tell me what you want to do with the Bootloader"
  echo "1. Unlock"
  echo "2. Lock"
  echo "Select then press enter"
  read -r selection

  selection=${selection:-None}
  if [ "$selection" = 'None' ] ; then
    die
  fi

  if [ "$selection" = 1 ] ; then
    action "Unlocking Bootloader"
    "${BOXROOTDIR}/bin/fastboot" oem unlock
    ok
  fi

  if [ "$selection" = 2 ] ; then
    action "Locking Bootloader"
    "${BOXROOTDIR}/bin/fastboot" oem lock
    ok
  fi

}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_bootloader() {
# }

cmd_bootloader() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_bootloader "$@"
