#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box download"
  echo
}

main() {
  banner
  select_droid

  bot "Select Android Version"
  echo "1. Android 4.4 (krt16s)"
  echo "2. Android 5.1.1 (lmy48t)"
  echo "3. Android 6.0.1 (mob30j)"
  echo "Select then press enter"
  read version

  # 2012 Nexus 7 Wifi Only Model (grouper)
  if [ $device = 1 ] ; then
    # 4.4   (KRT16S)
    if [ $version = 1 ] ; then
      image_archive='nakasi-krt16s-factory-da7dee49.tgz'
      image_sha1='da7dee497bc343fb8ed15995ccb0692123ee2eab'
    fi
    # 5.1.1 (LMY47V)
    if [ $version = 2 ] ; then
      image_archive='nakasi-lmy47v-factory-b48bd71d.tgz'
      image_sha1='b48bd71d1e6686fc68cd7fa9c17c18d7c4d078df'
    fi
    # 6.0.1
    if [ $version = 3 ] ; then
      die "Android 6.0.1 not availabe for this model"
    fi
  fi

  # 2013 Nexus 7 Wifi Only Model (flo)
  if [ $device = 2 ] ; then
    # 4.4   (krt16s)
    if [ $version = 1 ] ; then
      image_archive='razor-krt16s-factory-7235eb0d.tgz'
      image_sha1='7235eb0d1a967e8b37a38fe76764812c985b4702'
    fi
    # 5.1.1 (lmy48t)
    if [ $version = 2 ] ; then
      image_archive='razor-lmy48t-factory-b6a844f2.tgz'
      image_sha1='b6a844f2325d78546f263878f6bdcea95274dcf6'
    fi
    # 6.0.1 (mob30j)
    if [ $version = 3 ] ; then
      image_archive='razor-mob30j-factory-a2878e21.tgz'
      image_sha1='a2878e214754876f626b9e1c88ecec091581f2a6'
    fi
  fi

  # 2013 Nexus 7 LTE Model (deb)
  if [ $device = 3 ] ; then
    # 4.4   (krt16s)
    if [ $version = 1 ] ; then
      image_archive='razorg-krt16s-factory-bd6c9241.tgz'
      image_sha1='bd6c92418035598c0815d19a2b21066d3f6fe9b6'
    fi
    # 5.1.1 (lmy48t)
    if [ $version = 2 ] ; then
      image_archive='razorg-lmy48z-factory-68da1543.tgz'
      image_sha1='68da15436818726f73eda11b5b06c7818b7bd939'
    fi
    # 6.0.1 (mob30j)
    if [ $version = 3 ] ; then
      image_archive='razorg-mob30j-factory-976a9821.tgz'
      image_sha1='976a98215dcbe0ca1bf3bd50efa39e870a4b67fd'
    fi
  fi

  get_platform

  if [ "$NS_PLATFORM" == "darwin" ]; then
    sha_cmd='shasum'
  else
    sha_cmd='sha1sum'
  fi

  bot "Download Factory Image"
  running "https://dl.google.com/dl/android/aosp/$image_archive"
  wget -nc https://dl.google.com/dl/android/aosp/$image_archive -P $_DROID_ROOT/share/

  bot "Checking Download Integrity"
  downloaded=`$sha_cmd $_DROID_ROOT/share/$image_archive | awk '{ print $1 }'`
  warn "expected: $image_sha1"
  warn "     got: $downloaded"

  if [ $downloaded == $image_sha1 ]; then
    bot "Unpacking Factory Image"
    tar zxvf $_DROID_ROOT/share/$image_archive -C $_DROID_ROOT/share/
  else
    error "downloaded file did not verify"
    # rm -rf $_DROID_ROOT/share/$image_archive
  fi


  bot "Download Recovery Images"
  wget -nc http://download2.clockworkmod.com/recoveries/$clockwork -P $_DROID_ROOT/share/
  wget -nc https://dl.twrp.me/$product/$teamwin -P $_DROID_ROOT/share/
}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_download() {
# }

cmd_download() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_download "$@"
