#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box recovery"
  echo
}

main() {
  banner

  bot "Place your device in FASTBOOT MODE!"
  warn "Power off your device"
  warn "Power on device while holding volume down"
  read -rp "Press enter to continue"

  select_droid

  bot "Which Recovery Tool would you like to install"
    echo "1. ClockWorkMod https://www.clockworkmod.com/rommanager"
    echo "2. TeamWinRecovery https://twrp.me/devices/"
    echo "Select then press enter"
    read -r recovery

    if [ "$recovery" = 1 ] ; then
      # shellcheck disable=SC2154
      "${BOXROOTDIR}/bin/fastboot" flash recovery "${BOXROOTDIR}/share/$clockwork"
    fi
    if [ "$recovery" = 2 ] ; then
      # shellcheck disable=SC2154
      "${BOXROOTDIR}/bin/fastboot" flash recovery "${BOXROOTDIR}/share/$teamwin"
    fi

  bot "Boot to recovery"
    echo "Use the volume keys to highlight Recovery Mode,"
    echo "Use the power button to select it."
}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_recovery() {
# }

cmd_recovery() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_recovery "$@"
