#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box pibox adafruit"
  echo
}

main() {
  banner
  bot "Install Adafruit Python Examples"

  action "Cloning Git Repo"
  git clone https://github.com/adafruit/Adafruit-Raspberry-Pi-Python-Code.git /home/pi/Adafruit-Raspberry-Pi-Python-Code
  ok
}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_adafruit() {
# }

cmd_adafruit() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_adafruit "$@"
