#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box pibox camera"
  echo
}

main() {
  banner

  bot "Enable/Disable Camera"

  echo " 0. Disable camera"
  echo " 1. Enable camera"
  echo "Select then press enter"
  read up

  if [ $up = 0 ] ; then
    dir='off'
  fi
  if [ $up = 1 ] ; then
    dir='on'
  fi

  action "Writing configuration"
  sudo _PIBOX_ROOT=$_PIBOX_ROOT $BOXROOTDIR/lib/pibox/camera $dir
  ok

}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_camera() {
# }

cmd_camera() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_camera "$@"
