#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box pibox demos"
  echo
}

main() {
  banner
  bot "Raspberry PI Built in Demos"
  echo "Choose a demo"
  echo " B. Compile Demos"
  echo " 1. Hello world"
  echo " 2. Hello video"
  echo " 3. Hello triangle"
  echo " 4. Hello fractal"
  echo " 5. Hello teapot"
  echo " 6. Hello audio"
  echo " 7. Hello FFT"
  echo " 8. Hello Font"
  echo " 9. Hello Tiger"
  echo "10. Hello Encode"
  echo "11. Hello JPEG"
  echo "12. Hello Video Cube"
  echo "13. Hello DispManX"
  echo "Select then press enter"
  read demo

  if [ $demo = 'B' ] ; then
    action "Compiling demos"
    ( cd /opt/vc/src/hello_pi && ./rebuild.sh 2>&1 )
    $_PIBOX_ROOT/bin/pibox demos
  fi

  if [ $demo = 1 ] ; then
    /opt/vc/src/hello_pi/hello_world/hello_world.bin
  fi

  if [ $demo = 2 ] ; then
    /opt/vc/src/hello_pi/hello_video/hello_video.bin test.h264
  fi

  if [ $demo = 3 ] ; then
    /opt/vc/src/hello_pi/hello_triangle/hello_triangle.bin
  fi

  if [ $demo = 4 ] ; then
    /opt/vc/src/hello_pi/hello_triangle2/hello_triangle2.bin
  fi

  if [ $demo = 5 ] ; then
    /opt/vc/src/hello_pi/hello_teapot/hello_teapot.bin
  fi

  if [ $demo = 6 ] ; then
    /opt/vc/src/hello_pi/hello_audio/hello_audio.bin
  fi

  if [ $demo = 7 ] ; then
    /opt/vc/src/hello_pi/hello_fft/hello_fft.bin
  fi

  if [ $demo = 8 ] ; then
    /opt/vc/src/hello_pi/hello_font/hello_font.bin
  fi

  if [ $demo = 9 ] ; then
    /opt/vc/src/hello_pi/hello_tiger/hello_tiger.bin
  fi

  if [ $demo = 10 ] ; then
    /opt/vc/src/hello_pi/hello_encode/hello_encode.bin
  fi

  if [ $demo = 11 ] ; then
    /opt/vc/src/hello_pi/hello_jpeg/hello_jpeg.bin
  fi

  if [ $demo = 12 ] ; then
    /opt/vc/src/hello_pi/hello_videocube/hello_videocube.bin
  fi

  if [ $demo = 13 ] ; then
    /opt/vc/src/hello_pi/hello_dispmanx/hello_dispmanx.bin
  fi

}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_demos() {
# }

cmd_demos() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_demos "$@"
