#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box pibox hifiberry"
  echo
}

main() {
  banner
  bot "Installing HifiBerry Component(s)"
  echo " 1. DAC/DAC+ Light"
  echo " 2. DAC+ standard/pro"
  echo " 3. Digi/Digi+"
  echo " 4. Amp/Amp+"
  echo "Select device and press enter"
  read hifiberry

  action "Writing Configuration"
  sudo _PIBOX_ROOT=$_PIBOX_ROOT $BOXROOTDIR/lib/pibox/hifiberry $hifiberry
  ok
}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_hifiberry() {
# }

cmd_hifiberry() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_hifiberry "$@"
