#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box pibox touchscreen"
  echo
}

main() {
  banner
  bot "Set touch screen orientation"

  echo " 0. Normal orientation"
  echo " 1. Rotate 90 degrees"
  echo " 2. Rotate 180 degrees"
  echo " 3. Rotate 270 degrees"
  echo "Select then press enter"
  read -r orientation

  action "Writing Configuration"
  sudo "_PIBOX_ROOT=$_PIBOX_ROOT" "${BOXROOTDIR}/lib/pibox/touchscreen" "$orientation"
  ok

}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_touchscreen() {
# }

cmd_touchscreen() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_touchscreen "$@"
