#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box pibox usb-current"
  echo
}

main() {
  banner
  bot "Set touch screen orientation"

  echo " 0. Normal current"
  echo " 1. Maximum current"
  echo "Select then press enter"
  read -r current

  action "Writing Configuration"
  sudo "_PITAP2_ROOT=$_PITAP2_ROOT" "$_PITAP2_ROOT/lib/max-usb-current" "$current"
  ok
}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_usb-current() {
# }

cmd_usb-current() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_usb-current "$@"
