#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box pibox wiringpi"
  echo
}

main() {
  banner
  bot "Install WiringPi bindings for Raspberry Pi"

  action "Cloning Git Repo"
  git clone git://git.drogon.net/wiringPi ~/wiringpi
  cd ~/wiringPi
  git pull origin
  ./build
  ok

  action "Test wiringPi’s installation"
  gpio -v
  gpio readall
  ok
}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_wiringpi() {
# }

cmd_wiringpi() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_wiringpi "$@"
