#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box iso2usb"
  echo
}

main() {
  echo "your work here"
# Download the desired file
# Open the Terminal (in /Applications/Utilities/ or query Terminal in Spotlight)
# Convert the .iso file to .img using the convert option of hdiutil:
# hdiutil convert -format UDRW -o /path/to/target.img /path/to/source.iso
# Note: OS X tends to put the .dmg ending on the output file automatically. Rename the file by typing:
# mv /path/to/target.img.dmg /path/to/target.img
# Run diskutil list to get the current list of devices
# Insert your flash media
# Run diskutil list again and determine the device node assigned to your flash media (e.g. /dev/disk2)
# Run diskutil unmountDisk /dev/diskN (replace N with the disk number from the last command - in the previous example, N would be 2)
# Execute sudo dd if=/path/to/downloaded.img of=/dev/rdiskN bs=1m (replace /path/to/downloaded.img with the path where the image file is located; for example, ./ubuntu.img or ./ubuntu.dmg).
# Note: Using /dev/rdisk instead of /dev/disk may be faster.
# Note: If you see the error dd: Invalid number '1m', you are using GNU dd. Use the same command but replace bs=1m with bs=1M.
# Note: If you see the error dd: /dev/diskN: Resource busy, make sure the disk is not in use. Start the 'Disk Utility.app' and unmount (don't eject) the drive.
Run diskutil eject /dev/diskN and remove your flash media when the command completes
}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_iso2usb() {
# }

cmd_iso2usb() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_iso2usb "$@"
