#!/usr/bin/env bash

usage() {
  echo "usage: box template"
  echo
}

main() {
  echo "$@"
}

_cmd_template() {
  # _values 'Options' \
  #   --skip-gemfile"[Don't create a Gemfile]" \
  #   --skip-bundle"[Don't run bundle install]"

  # _alternative \
  #   'args:custom args:(a b c)' \
  #   'files:filenames:_files'

  _alternative \
    'args:custom args:((a\:"description a" b\:"description b" c\:"description c"))' \
    'files:filenames:_files'

  # _alternative "dirs:user directories:($userdirs)" \
  #              "pids:process IDs:($(ps -A o pid=))"

  # _arguments '-s[sort output]' '--l[long output]' '-l[long output]'

  # _multi_parts : '(00:11:22:33:44:55 00:23:34:45:56:67 00:23:45:56:67:78)'
}

cmd_template() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_template "$@"
