#!/usr/bin/env bash
# Usage: pitap2 startup mode1
# Summary: Start the PiTap2 capture service
# Help:
# mode1 – creates a timestamped capture within the captures directory.
# mode2 – creates a subdirectory (for each “session”) and uses tcpdump log rotation.
# Each 10 minute dump is given a name dependent upon the Unix epoch from when it was created;
# therefore, each capture is individually timestamped.
# This is mainly being used for future development work, but some readers may find in useful in the intermittent period.

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

cmd_start() {
  ### PATH SETUP
  _PITAP2_CAPTURE_DIR=/mnt/data/captures
  _PITAP2_LOGFILE=/mnt/data/captures/pitap.log

  ### BRIDGE NETWORK INTERFACES
  # Create bridge and add interfaces.
  brctl addbr bridge0
  brctl addif bridge0 eth1
  brctl addif bridge0 eth2
  # Zero the IP addresses on the interfaces.
  ifconfig eth1 0.0.0.0
  ifconfig eth2 0.0.0.0
  # Start the bridge.
  ifconfig bridge0 up

  ### PACKET CAPTURE
  sessionTimestamp=$(date +"session-%d-%m-%y-at-%H-%M")

  if [ $1 = "mode1" ]; then

  	echo "Starting dump mode at $sessionTimestamp. Captures stored the base directory." >> $_PITAP2_LOGFILE
  	# MODE 1: WITHOUT sessions.
  	# Start capture in the base capture directory.
  	tcpdump -i bridge0 -w $_PITAP2_CAPTURE_DIR/$sessionTimestamp-$RANDOM.pcapng

  elif [ $1 = "mode2" ]; then

  	# MODE 2: WITH sessions.
  	# Create session-specific directory (with timestamp of session start).
  	# Captures are rotated every x seconds, and each capture is given a filename based upon the Unix timestamp of when it was created.
  	# Used for future development work within the PiTap project.
  	# Create session-specific folder based upon tiemstamp.
  	timestampedDirectory=$sessionTimestamp-$RANDOM
  	mkdir $_PITAP2_CAPTURE_DIR/$timestampedDirectory
  	# Start rotating captures in session-specific folder.
  	tcpdump -i bridge0 -w $_PITAP2_CAPTURE_DIR/$timestampedDirectory/dump-at-%s.pcapng -G 3600

  else

  	echo "PiTap2 has been configured to use an unknown mode!" >> $_PITAP2_LOGFILE

  fi
}
