#!/usr/bin/env bash
# Usage: pitap2 test-network
# Summary: automate the testing of newtork throughput
# Help:
#

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

cmd_test-network() {
  ######################################################################
  # testing network throughput
  # http://williamknowles.co.uk/?p=68
  echo "not implemented"
}
