#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box COMMANDNAME"
  echo
}

main() {
  banner
  get_platform

  if [ "$NS_PLATFORM" == "darwin" ]; then
    if [[ $1 != "--skip-gui" ]]; then
    fi
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
    if [[ $1 != "--skip-gui" ]]; then
    fi
  fi
}

_cmd_COMMANDNAME() {
  _values 'Params' \
    --skip-gui"[Skip installing the GUI applications]"
}

cmd_COMMANDNAME() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_COMMANDNAME "$@"
