#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box apt-file"
  echo
}

main() {
  docker run --rm -it \
  ${DOCKER_REPO_PREFIX}/apt-file
}

# _cmd_apt-file() {
# }

cmd_apt-file() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_apt-file "$@"
