#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box bees"
  echo
}

main() {
  docker run -it --rm \
  -e NOTARY_TOKEN \
  -v "${HOME}/.bees:/root/.bees" \
  -v "${HOME}/.boto:/root/.boto" \
  -v "${HOME}/.dev:/root/.ssh:ro" \
  --log-driver none \
  ${DOCKER_REPO_PREFIX}/beeswithmachineguns "$@"
}

# _cmd_bees() {
# }

cmd_bees() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_bees "$@"
