#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box cheese"
  echo
}

main() {
  local RUNASNAME="cheese"
  del_stopped $RUNASNAME
  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=unix${DISPLAY}" \
  -v "${HOME}/Pictures:/root/Pictures" \
  --device /dev/video0 \
  --device /dev/snd \
  --device /dev/dri \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/cheese
}

# _cmd_cheese() {
# }

cmd_cheese() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_cheese "$@"
