#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box dcos-cli"
  echo
}

main() {
  docker run -it --rm \
  -v "${HOME}/.dcos:/root/.dcos" \
  -v "$(pwd):/root/apps" \
  -w /root/apps \
  ${DOCKER_REPO_PREFIX}/dcos-cli "$@"
}

# _cmd_dcos-cli() {
# }

cmd_dcos-cli() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_dcos-cli "$@"
