#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box dgcloud"
  echo
}

main() {
  docker run --rm -it \
  -v "${HOME}/.gcloud:/root/.config/gcloud" \
  -v "${HOME}/.ssh:/root/.ssh:ro" \
  -v "$(which docker):/usr/bin/docker" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  ${DOCKER_REPO_PREFIX}/gcloud "$@"
}

# _cmd_dgcloud() {
# }

cmd_dgcloud() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_dgcloud "$@"
