#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box firefox"
  echo
}

main() {
  local container_name="firefox"
  del_stopped $container_name
  docker run -d \
  --memory 2gb \
  --net host \
  --cpuset-cpus 0 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v "${HOME}/.firefox/cache:/root/.cache/mozilla" \
  -v "${HOME}/.firefox/mozilla:/root/.mozilla" \
  -v "${HOME}/Downloads:/root/Downloads" \
  -v "${HOME}/Pictures:/root/Pictures" \
  -v "${HOME}/Torrents:/root/Torrents" \
  -e "DISPLAY=${DISPLAY}" \
  -e GDK_SCALE \
  -e GDK_DPI_SCALE \
  --device /dev/snd \
  --device /dev/dri \
  --name $container_name \
  ${DOCKER_REPO_PREFIX}/firefox "$@"

  # exit current shell
  exit 0
}

# _cmd_firefox() {
# }

cmd_firefox() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_firefox "$@"
