#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box gcalcli"
  echo
}

main() {
  docker run --rm -it \
  -v /etc/localtime:/etc/localtime:ro \
  -v "${HOME}/.gcalcli/home:/home/gcalcli/home" \
  -v "${HOME}/.gcalcli/work/oauth:/home/gcalcli/.gcalcli_oauth" \
  -v "${HOME}/.gcalcli/work/gcalclirc:/home/gcalcli/.gcalclirc" \
  "${DOCKER_REPO_PREFIX}/gcalcli" "$@"
}

# _cmd_gcalcli() {
# }

cmd_gcalcli() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_gcalcli "$@"
