#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box docker hollywood"
  echo
}

main() {
  local container_name="hollywood"
  del_stopped $container_name
  docker run --rm -it \
  --name "$container_name" \
  "${DOCKER_REPO_PREFIX}/hollywood"
}

# _cmd_hollywood() {
# }

cmd_hollywood() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_hollywood "$@"
