#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box httpie"
  echo
}

main() {
  local container_name="httpie"
  del_stopped $container_name
  docker run -t --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --name $container_name \
  --log-driver none \
  ${DOCKER_REPO_PREFIX}/httpie "$@"
}

# _cmd_httpie() {
# }

cmd_httpie() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_httpie "$@"
