#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box imagemin"
  echo
}

main() {
  local RUNASNAME="imagemin"
  del_stopped $RUNASNAME
  local image=$1
  local extension="${image##*.}"
  local filename="${image%.*}"
  
  docker run --rm -it \
  -v /etc/localtime:/etc/localtime:ro \
  -v "${HOME}/Pictures:/root/Pictures" \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/imagemin sh -c "imagemin /root/Pictures/${image} > /root/Pictures/${filename}_min.${extension}"
}

_cmd_imagemin() {
  _alternative "image:Image Path:_files"
}

cmd_imagemin() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_imagemin "$@"
