#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box irssi"
  echo
}

main() {
  local RUNASNAME="irssi"
  del_stopped $RUNASNAME
  # relies_on notify_osd

  docker run --rm -it \
  -v /etc/localtime:/etc/localtime:ro \
  -v "${HOME}/.irssi:/home/user/.irssi" \
  --read-only \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/irssi
}

# _cmd_irssi() {
# }

cmd_irssi() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_irssi "$@"
