#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box john"
  echo
}

main() {
  container_name="john"

  local file
  file=$(realpath "$1")

  docker run --rm -it \
  -v "${file}:/root/$(basename "${file}")" \
  --name "$container_name" \
  "${DOCKER_REPO_PREFIX}/john" "$@"
}

# _cmd_john() {
# }

cmd_john() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_john "$@"
