#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box kernel-builder"
  echo
}

main() {
  docker run --rm -it \
  -v /usr/src:/usr/src \
  --cpu-shares=512 \
  --name kernel-builder \
  ${DOCKER_REPO_PREFIX}/kernel-builder
}

# _cmd_kernel-builder() {
# }

cmd_kernel-builder() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_kernel-builder "$@"
