#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box kvm"
  echo
}

main() {
  local container_name='kvm'
  del_stopped $container_name
  relies_on pulseaudio

  # modprobe the module
  modprobe kvm

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /run/libvirt:/var/run/libvirt \
  -e "DISPLAY=${DISPLAY}" \
  --link pulseaudio:pulseaudio \
  -e PULSE_SERVER=pulseaudio \
  --group-add audio \
  --name $container_name \
  --privileged \
  ${DOCKER_REPO_PREFIX}/kvm

}

# _cmd_kvm() {
# }

cmd_kvm() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_kvm "$@"
