#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box libreoffice"
  echo
}

main() {
  local container_name='libreoffice'
  del_stopped $container_name

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=${DISPLAY}" \
  -v "${HOME}/slides:/root/slides" \
  -e GDK_SCALE \
  -e GDK_DPI_SCALE \
  --name "$container_name" \
  "${DOCKER_REPO_PREFIX}/libreoffice"
}

# _cmd_libreoffice() {
# }

cmd_libreoffice() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_libreoffice "$@"
