#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box lynx"
  echo
}

main() {
  docker run --rm -it \
  --name lynx \
  "${DOCKER_REPO_PREFIX}/lynx" "$@"
}

# _cmd_lynx() {
# }

cmd_lynx() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_lynx "$@"
