#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box masscan"
  echo
}

main() {
  docker run -it --rm \
  --log-driver none \
  --net host \
  --cap-add NET_ADMIN \
  --name masscan \
  "${DOCKER_REPO_PREFIX}/masscan" "$@"
}

# _cmd_masscan() {
# }

cmd_masscan() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_masscan "$@"
