#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box mpd"
  echo
}

main() {
  local container_name='mpd'
  del_stopped $container_name

  # adding cap sys_admin so I can use nfs mount
  # the container runs as a unpriviledged user mpd
  docker run -d \
  --device /dev/snd \
  --cap-add SYS_ADMIN \
  -e MPD_HOST=/var/lib/mpd/socket \
  -v /etc/localtime:/etc/localtime:ro \
  -v /etc/exports:/etc/exports:ro \
  -v "${HOME}/.mpd:/var/lib/mpd" \
  -v "${HOME}/.mpd.conf:/etc/mpd.conf" \
  --name $container_name \
  ${DOCKER_REPO_PREFIX}/mpd
}

# _cmd_mpd() {
# }

cmd_mpd() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_mpd "$@"
