#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box ncmpc"
  echo
}

main() {
  local container_name='ncmpc'
  del_stopped $container_name

  docker run --rm -it \
  -v "${HOME}/.mpd/socket:/var/run/mpd/socket" \
  -e MPD_HOST=/var/run/mpd/socket \
  --name $container_name \
  ${DOCKER_REPO_PREFIX}/ncmpc "$@"
}

# _cmd_ncmpc() {
# }

cmd_ncmpc() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_ncmpc "$@"
