#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box nes"
  echo
}

main() {
  local container_name='nes'
  del_stopped $container_name
  local game=$1

  docker run -d \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=unix${DISPLAY}" \
  --device /dev/dri \
  --device /dev/snd \
  --name $container_name \
  ${DOCKER_REPO_PREFIX}/nes "/games/${game}.rom"
}

# _cmd_nes() {
# }

cmd_nes() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_nes "$@"
