#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box nginx"
  echo
}

main() {
  local RUNASNAME='nginx'
  del_stopped $RUNASNAME
  
  docker run -d \
  --restart always \
  -v "${HOME}/.nginx:/etc/nginx" \
  --net host \
  --name $RUNASNAME \
  nginx
  
  # add domain to hosts & open nginx
  sudo hostess add jess 127.0.0.1
  # TODO: WTF is hostess?
}

# _cmd_nginx() {
# }

cmd_nginx() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_nginx "$@"
