#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box notify-osd"
  echo
}

main() {
  local RUNASNAME='notify_osd'
  del_stopped $RUNASNAME

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  --net none \
  -v /etc \
  -v /home/user/.dbus \
  -v /home/user/.cache/dconf \
  -e "DISPLAY=unix${DISPLAY}" \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/notify-osd
}

# _cmd_notify-osd() {
# }

cmd_notify-osd() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_notify-osd "$@"
