#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box pandoc"
  echo
}

main() {
  local file=${*: -1}
  local lfile
  lfile=$(readlink -m "$(pwd)/${file}")
  local rfile
  rfile=$(readlink -m "/$(basename "$file")")
  local args=${*:1:${#@}-1}

  docker run --rm \
  -v "${lfile}:${rfile}" \
  -v /tmp:/tmp \
  --name pandoc \
  "${DOCKER_REPO_PREFIX}/pandoc" "${args}" "${rfile}"

}

# _cmd_pandoc() {
# }

cmd_pandoc() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_pandoc "$@"
