#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box pivman"
  echo
}

main() {
  local RUNASNAME='pivman'
  del_stopped $RUNASNAME

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=unix${DISPLAY}" \
  --device /dev/bus/usb \
  --device /dev/usb \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/pivman

}

# _cmd_pivman() {
# }

cmd_pivman() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_pivman "$@"
