#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box pond"
  echo
}

main() {
  local container_name='pond'
  del_stopped $container_name
  relies_on torproxy

  docker run --rm -it \
  --net container:torproxy \
  --name "$container_name" \
  "${DOCKER_REPO_PREFIX}/pond"

}

# _cmd_pond() {
# }

cmd_pond() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_pond "$@"
