#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box privoxy"
  echo
}

main() {
  local RUNASNAME='privoxy'
  del_stopped $RUNASNAME
  relies_on torproxy
  
  docker run -d \
  --restart always \
  --link torproxy:torproxy \
  -v /etc/localtime:/etc/localtime:ro \
  -p 8118:8118 \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/privoxy
  
  hostess add privoxy "$(docker inspect --format '{{.NetworkSettings.Networks.bridge.IPAddress}}' privoxy)"
  
}

# _cmd_privoxy() {
# }

cmd_privoxy() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_privoxy "$@"
