#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box pulseaudio"
  echo
}

main() {
  local container_name='pulseaudio'
  del_stopped $container_name

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  --device /dev/snd \
  -p 4713:4713 \
  --restart always \
  --group-add audio \
  --name $container_name \
  ${DOCKER_REPO_PREFIX}/pulseaudio
}

# _cmd_pulseaudio() {
# }

cmd_pulseaudio() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_pulseaudio "$@"
