#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box rainbowstream"
  echo
}

main() {
  docker run -it --rm \
  -v /etc/localtime:/etc/localtime:ro \
  -v "${HOME}/.rainbow_oauth:/root/.rainbow_oauth" \
  -v "${HOME}/.rainbow_config.json:/root/.rainbow_config.json" \
  --name rainbowstream \
  "${DOCKER_REPO_PREFIX}/rainbowstream"

}

# _cmd_rainbowstream() {
# }

cmd_rainbowstream() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_rainbowstream "$@"
