#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box registrator"
  echo
}

main() {
  local RUNASNAME='registrator'
  del_stopped $RUNASNAME
  
  docker run -d --restart always \
  -v /var/run/docker.sock:/tmp/docker.sock \
  --net host \
  --name $RUNASNAME \
  gliderlabs/registrator consul:
  
}

# _cmd_registrator() {
# }

cmd_registrator() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_registrator "$@"
