#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box remmina"
  echo
}

main() {
  local container_name='remmina'
  del_stopped $container_name

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=unix${DISPLAY}" \
  -e GDK_SCALE \
  -e GDK_DPI_SCALE \
  -v "${HOME}/.remmina:/root/.remmina" \
  --name $container_name \
  --net host \
  ${DOCKER_REPO_PREFIX}/remmina

}

# _cmd_remmina() {
# }

cmd_remmina() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_remmina "$@"
