#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box s3cmdocker"
  echo
}

main() {
  local container_name='s3cmd'
  del_stopped $container_name

  docker run --rm -it \
  -e AWS_ACCESS_KEY="${DOCKER_AWS_ACCESS_KEY}" \
  -e AWS_SECRET_KEY="${DOCKER_AWS_ACCESS_SECRET}" \
  -v "$(pwd):/root/s3cmd-workspace" \
  --name #container_name \
  "${DOCKER_REPO_PREFIX}/s3cmd" "$@"
}

# _cmd_s3cmdocker() {
# }

cmd_s3cmdocker() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_s3cmdocker "$@"
