#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box scudcloud"
  echo
}

main() {
  local container_name='scudcloud'
  del_stopped $container_name

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=unix${DISPLAY}" \
  -v /etc/machine-id:/etc/machine-id:ro \
  -v /var/run/dbus:/var/run/dbus \
  -v "/var/run/user/$(id -u):/var/run/user/$(id -u)" \
  -e TERM \
  -e XAUTHORITY \
  -e DBUS_SESSION_BUS_ADDRESS \
  -e HOME \
  -e QT_DEVICE_PIXEL_RATIO \
  -v /etc/passwd:/etc/passwd:ro \
  -v /etc/group:/etc/group:ro \
  -u "$(whoami)" -w "$HOME" \
  -v "${HOME}/.Xauthority:$HOME/.Xauthority" \
  -v /etc/machine-id:/etc/machine-id:ro \
  -v "${HOME}/.scudcloud:/home/jessie/.config/scudcloud" \
  --device /dev/snd \
  --name $container_name \
  ${DOCKER_REPO_PREFIX}/scudcloud

  # exit current shell
  exit 0
}

# _cmd_scudcloud() {
# }

cmd_scudcloud() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_scudcloud "$@"
