#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box shorewall"
  echo
}

main() {
  local RUNASNAME='shorewall'
  del_stopped $RUNASNAME
  
  docker run --rm -it \
  --net host \
  --cap-add NET_ADMIN \
  --privileged \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/shorewall "$@"
  
}

# _cmd_shorewall() {
# }

cmd_shorewall() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_shorewall "$@"
