#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box slack"
  echo
}

main() {
  local RUNASNAME='slack'
  del_stopped $RUNASNAME

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=unix${DISPLAY}" \
  --device /dev/snd \
  --device /dev/dri \
  --device /dev/video0 \
  --group-add audio \
  --group-add video \
  -v "${HOME}/.slack:/root/.config/Slack" \
  --ipc="host" \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/slack "$@"

}

# _cmd_slack() {
# }

cmd_slack() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_slack "$@"
