#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box spotify"
  echo
}

main() {
  local container_name='spotify'
  del_stopped $container_name

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=${DISPLAY}" \
  -e QT_DEVICE_PIXEL_RATIO \
  --security-opt seccomp:unconfined \
  --device /dev/snd \
  --device /dev/dri \
  --group-add audio \
  --group-add video \
  --name $container_name \
  ${DOCKER_REPO_PREFIX}/spotify

}

# _cmd_spotify() {
# }

cmd_spotify() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_spotify "$@"
