#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box ssh2john"
  echo
}

main() {
  local file
  file=$(realpath "$1")

  docker run --rm -it \
  -v "${file}:/root/$(basename "${file}")" \
  --entrypoint ssh2john \
  "${DOCKER_REPO_PREFIX}/john" "$@"

}

# _cmd_ssh2john() {
# }

cmd_ssh2john() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_ssh2john "$@"
