#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box steam"
  echo
}

main() {
  local container_name='spotify'
  del_stopped $container_name
  relies_on pulseaudio

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /etc/machine-id:/etc/machine-id:ro \
  -v /var/run/dbus:/var/run/dbus \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v "${HOME}/.steam:/home/steam" \
  -e "DISPLAY=${DISPLAY}" \
  --link pulseaudio:pulseaudio \
  -e PULSE_SERVER=pulseaudio \
  --device /dev/dri \
  --name container_name \
  ${DOCKER_REPO_PREFIX}/steam

}

# _cmd_steam() {
# }

cmd_steam() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_steam "$@"
