#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box t"
  echo
}

main() {
  docker run -t --rm \
  -v "${HOME}/.trc:/root/.trc" \
  --log-driver none \
  ${DOCKER_REPO_PREFIX}/t "$@"

}

# _cmd_t() {
# }

cmd_t() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_t "$@"
