#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box tarsnap"
  echo
}

main() {
  docker run --rm -it \
  -v "${HOME}/.tarsnaprc:/root/.tarsnaprc" \
  -v "${HOME}/.tarsnap:/root/.tarsnap" \
  -v "$HOME:/root/workdir" \
  ${DOCKER_REPO_PREFIX}/tarsnap "$@"
  
}

# _cmd_tarsnap() {
# }

cmd_tarsnap() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_tarsnap "$@"
