#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box termboy"
  echo
}

main() {
  local container_name='termboy'
  del_stopped $container_name

  local game=$1

  docker run --rm -it \
  --device /dev/snd \
  --name "$container_name" \
  "${DOCKER_REPO_PREFIX}/nes" "/games/${game}.rom"

}

# _cmd_termboy() {
# }

cmd_termboy() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_termboy "$@"
