#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box tor"
  echo
}

main() {
  local RUNASNAME='tor'
  del_stopped $RUNASNAME

  docker run -d \
  --net host \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/tor

  # set up the redirect iptables rules
  sudo setup-tor-iptables

  # validate we are running through tor
  browser-exec "https://check.torproject.org/"

}

# _cmd_tor() {
# }

cmd_tor() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_tor "$@"
