#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box tormessenger"
  echo
}

main() {
  local RUNASNAME='tormessenger'
  del_stopped $RUNASNAME
  
  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=unix${DISPLAY}" \
  -e GDK_SCALE \
  -e GDK_DPI_SCALE \
  --device /dev/snd \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/tor-messenger
  
  # exit current shell
  exit 0
  
}

# _cmd_tormessenger() {
# }

cmd_tormessenger() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_tormessenger "$@"
