#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box torproxy"
  echo
}

main() {
  local RUNASNAME='torproxy'
  del_stopped $RUNASNAME

  docker run -d \
  --restart always \
  -v /etc/localtime:/etc/localtime:ro \
  -p 9050:9050 \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/tor-proxy

  hostess add torproxy "$(docker inspect --format '{{.NetworkSettings.Networks.bridge.IPAddress}}' torproxy)"

}

# _cmd_torproxy() {
# }

cmd_torproxy() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_torproxy "$@"
