#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box transmission"
  echo
}

main() {
  local container_name='transmission'
  del_stopped $container_name

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v "${HOME}/Torrents:/transmission/download" \
  -v "${HOME}/.transmission:/transmission/config" \
  -p 9091:9091 \
  -p 51413:51413 \
  -p 51413:51413/udp \
  --name $container_name \
  ${DOCKER_REPO_PREFIX}/transmission


  hostess add transmission "$(docker inspect --format '{{.NetworkSettings.Networks.bridge.IPAddress}}' transmission)"
  browser-exec "http://transmission:9091"

}

# _cmd_transmission() {
# }

cmd_transmission() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_transmission "$@"
