#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box travis"
  echo
}

main() {
  docker run -it --rm \
  -v "${HOME}/.travis:/root/.travis" \
  -v $(pwd):/usr/src/repo:ro \
  --workdir /usr/src/repo \
  --log-driver none \
  ${DOCKER_REPO_PREFIX}/travis "$@"

}

# _cmd_travis() {
# }

cmd_travis() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_travis "$@"
