#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box virsh"
  echo
}

main() {
  relies_on kvm
  
  docker run -it --rm \
  -v /etc/localtime:/etc/localtime:ro \
  -v /run/libvirt:/var/run/libvirt \
  --log-driver none \
  --net container:kvm \
  ${DOCKER_REPO_PREFIX}/libvirt-client "$@"
  
}

# _cmd_virsh() {
# }

cmd_virsh() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_virsh "$@"
