#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box virt-viewer"
  echo
}

main() {
  relies_on kvm
  
  docker run -it --rm \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix  \
  -e "DISPLAY=unix${DISPLAY}" \
  -v /run/libvirt:/var/run/libvirt \
  -e PULSE_SERVER=pulseaudio \
  --group-add audio \
  --log-driver none \
  --net container:kvm \
  ${DOCKER_REPO_PREFIX}/virt-viewer "$@"
  
}

# _cmd_virt-viewer() {
# }

cmd_virt-viewer() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_virt-viewer "$@"
