#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box visualstudio"
  echo
}

main() {
  local RUNASNAME='visualstudio'
  del_stopped $RUNASNAME
  
  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix  \
  -e "DISPLAY=unix${DISPLAY}" \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/vscode
}

# _cmd_visualstudio() {
# }

cmd_visualstudio() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_visualstudio "$@"
