#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box vlc"
  echo
}

main() {
  local container_name='vlc'
  del_stopped $container_name
  relies_on pulseaudio

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=${DISPLAY}" \
  -e GDK_SCALE \
  -e GDK_DPI_SCALE \
  -e QT_DEVICE_PIXEL_RATIO \
  --link pulseaudio:pulseaudio \
  -e PULSE_SERVER=pulseaudio \
  --group-add audio \
  --group-add video \
  -v "${HOME}/Torrents:/home/vlc/Torrents" \
  --device /dev/dri \
  --name "$container_name" \
  "${DOCKER_REPO_PREFIX}/vlc"
}

# _cmd_vlc() {
# }

cmd_vlc() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_vlc "$@"
