#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box watchman"
  echo
}

main() {
  local RUNASNAME='watchman'
  del_stopped $RUNASNAME

  docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v "${HOME}/Downloads:/root/Downloads" \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/watchman --foreground

}

# _cmd_watchman() {
# }

cmd_watchman() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_watchman "$@"
