#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box weeslack"
  echo
}

main() {
  local RUNASNAME='weeslack'
  del_stopped $RUNASNAME
  
  docker run --rm -it \
  -v /etc/localtime:/etc/localtime:ro \
  -v "${HOME}/.weechat:/home/user/.weechat" \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/wee-slack
  
}

# _cmd_weeslack() {
# }

cmd_weeslack() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0
    
    elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0
    
    elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi
    
    main $1; exit 0
  fi
  
  usage; exit 1
}

# cmd_weeslack "$@"
