#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box ykpersonalize"
  echo
}


main() {
  local container_name='ykpersonalize'
  del_stopped $container_name

  docker run --rm -it \
  -v /etc/localtime:/etc/localtime:ro \
  --device /dev/usb \
  --device /dev/bus/usb \
  --name "$container_name" \
  "${DOCKER_REPO_PREFIX}/ykpersonalize" bash

}

# _cmd_ykpersonalize() {
# }

cmd_ykpersonalize() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_ykpersonalize "$@"
