#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box ykprivtool"
  echo
}

main() {
  local RUNASNAME='yubico-piv-tool'
  del_stopped $RUNASNAME

  docker run --rm -it \
  -v /etc/localtime:/etc/localtime:ro \
  --device /dev/usb \
  --device /dev/bus/usb \
  --name $RUNASNAME \
  ${DOCKER_REPO_PREFIX}/yubico-piv-tool bash

}

# _cmd_ykprivtool() {
# }

cmd_ykprivtool() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_ykprivtool "$@"
