#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

config=/boot/config.txt

[ -e "${config}" ] || touch "${config}"

if [ "$1" = 'off' ] ; then
  sed "${config}" -i -e "s/^start_x=1//"
  sed "${config}" -i -e "s/^gpu_mem=128//"
fi

if [ "$1" = 'on' ] ; then
  set_config_var start_x 1 "${config}"
  set_config_var gpu_mem 128 "${config}"
  sed "${config}" -i -e "s/^startx/#startx/"
  sed "${config}" -i -e "s/^fixup_file/#fixup_file/"
fi

exit
