#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box proj ansible [project_name]"
  echo
}

main() {
  # banner
  local project_name="$1"

  ###########################################################
  bot "Cloning Ansible Project Skeleton"
  git clone https://github.com/russelltsherman/proj-ansible.git "$project_name"
  ok

  running "purging upstream git history"
  ( cd "$project_name" && rm -rf .git )
  ok

  running "initialize new git repo"
  ( cd "$project_name" && git init &>/dev/null )
  ok

  running "initial git commit"
  ( cd "$project_name" && git add . && git commit -a -m 'initial commit' )
  ok
}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_ansible() {
# }

cmd_ansible() {
  if [ "$#" -eq 0 ] ; then
    usage; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_ansible "$@"
