#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box docker [project_name]"
  echo
}

main() {
  banner
  local project_name=$1

  running "create project directory"
  mkdir -p $project_name
  ok

  running "initialize git"
  ( cd $project_name && git init &>/dev/null )
  gibo docker > $project_name/.gitignore
  cp $BOXROOTDIR/lib/gitattributes_template $project_name/.gitattributes
  ok

  running "write .editorconfig"
  cp $BOXROOTDIR/lib/editorconfig_template $project_name/.editorconfig
  ok

  running "write README.md"
  echo "# $project_name" > $project_name/README.md
  ok

  running "write TODO.md"
  echo "# $project_name" > $project_name/TODO.md
  ok

  running "write .dockerignore"
  echo "
.git
.docker_env
.editorconfig
.gitattributes
.gitignore
TODO.md
  " > $project_name/.dockerignore
  ok

  running "write Dockerfile"
  touch $project_name/Dockerfile
  ok

  running "write docker-compose.yml"
  touch $project_name/docker-compose.yml
  ok

  running "write .docker_env"
  touch $project_name/.docker_env
  ok

  running "write Makefile"
  touch $project_name/.docker_env
  ok

}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_docker() {
# }

cmd_docker() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_docker "$@"
