#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box docker [project_name]"
  echo
}

main() {
  banner

  local project_name=$1

  ###########################################################
  action "create project directory"
    mkdir -p $project_name
  ok

  ###########################################################
  action "initialize"
    # create gitignore
    gibo docker > $project_name/.gitignore

    # create README.md
    touch $project_name/README.md
    echo "# $project_name" > $project_name/README.md
    # create dockerignore
    touch $project_name/.dockerignore
    echo '.git' > $project_name/.dockerignore
    echo '.dockerignore' > $project_name/.dockerignore
    # create dockerfile
    touch $project_name/Dockerfile
    # create docker-compose.yml
    touch $project_name/docker-compose.yml
    # create a .docker_env
    touch $project_name/.docker_env
  ok

}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_docker() {
# }

cmd_docker() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_docker "$@"
