#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box proj golang [project name] [go version]"
  echo
}

main() {
  banner
  get_platform
  local project_name=$1
  local version=$2
  local file=go$version.$NS_PLATFORM-amd64

  running "create project directory"
  mkdir -p $project_name/{bin,pkg,src}
  ok

  running "initialize git"
  ( cd $project_name && git init &>/dev/null )
  gibo go > $project_name/.gitignore
  cp $BOXROOTDIR/lib/gitattributes_template $project_name/.gitattributes
  ok

  running "write .editorconfig"
  echo "
# unifying the coding style for different editors and IDEs => editorconfig.org
; indicate this is the root of the project
root = true

###########################################################
; common
###########################################################
[*]
charset = utf-8

end_of_line = LF
insert_final_newline = true
trim_trailing_whitespace = true

indent_style = space
indent_size = 2

###########################################################
; make
###########################################################
[Makefile]
indent_style = tab

###########################################################
; markdown
###########################################################
[*.md]
trim_trailing_whitespace = false

###########################################################
; golang
###########################################################
[*.go]
indent_style = tab
" > $project_name/.editorconfig
  ok

  running "write README.md"
  echo "# $project_name" > $project_name/README.md
  ok

  running "write TODO.md"
  echo "# $project_name" > $project_name/TODO.md
  ok

  running "write .envrc"
  touch $project_name/.envrc
  echo "
layout gb
" > $project_name/.envrc

  running "download golang archive"
  wget -O $project_name/$file.tar.gz https://storage.googleapis.com/golang/$file.tar.gz
  tar -xvzf $project_name/$file.tar.gz -C $project_name
  cp -r $project_name/go/bin $project_name
  rm -rf $project_name/$file.tar.gz
  rm -rf $project_name/go
  ok

  running "initial git commit"
  ( cd $project_name && git add . && git commit -a -m 'initial commit' )
  ok
}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
_cmd_golang() {
  _alternative "go_version:Go Version:(1.5.3 1.6.4 1.7.5)"
}

cmd_golang() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  fi

  usage; exit 1
}

# cmd_golang "$@"
