#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box node [project_name] [node_version]"
  echo
}

main() {
  banner
  local project_name=$1
  local version=$2

  running "create project directory"
  mkdir -p $project_name
  ok

  running "initialize git"
  ( cd $project_name && git init &>/dev/null )
  gibo node > $project_name/.gitignore
  cp $BOXROOTDIR/lib/gitattributes_template $project_name/.gitattributes
  ok

  running "write .editorconfig"
  cp $BOXROOTDIR/lib/editorconfig_template $project_name/.editorconfig
  ok

  running "write README.md"
  echo "## $project_name" > $project_name/README.md
  ok

  running "write TODO.md"
  echo "## $project_name" > $project_name/TODO.md
  ok

  running "write autoenv files"
  touch $project_name/.env
  echo "
nvm use $version
export OLDPATH=\$PATH
export PATH=\`pwd\`/node_modules/.bin:\$PATH
" > $project_name/.env

  touch $project_name/.out
  echo "
nvm use system
export PATH=\$OLDPATH
" > $project_name/.out
  ok

  running "initialize NPM"
  ( cd $project_name && npm init )
  ok

}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_node() {
#   _alternative "node_version:NodeJS Version:(4.7.2 5.12.0 6.9.4 7.2.0)"
# }

cmd_node() {
  if [ "$#" -lt 2 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -eq 2 ]; then # called with 2 parameters
    main "$@"; exit 0
  fi

  usage; exit 1
}

# cmd_node "$@"
