#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box proj polymer [project_name]"
  echo
}

main() {
  # banner
  local project_name=$1

  ###########################################################
  bot "Cloning Polymer Project Skeleton"
  git clone https://github.com/russelltsherman/proj-polymer.git $project_name
  ok

  running "purging upstream git history"
  ( cd $project_name && rm -rf .git )
  ok

  running "initialize new git repo"
  ( cd $project_name && git init &>/dev/null )
  ok

  running "initial git commit"
  ( cd $project_name && git add . && git commit -a -m 'initial commit' )
  ok

  running "initialize dev dependencies"
  ( cd $project_name && npm install )
  ok
}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_polymer() {
#   _alternative "node_version:NodeJS Version:(4.7.2 5.12.0 6.9.4 7.2.0)"
# }

cmd_polymer() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    main "$@"; exit 0
  fi

  usage; exit 1
}

# cmd_node "$@"
