#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box vagrant [project_name]"
  echo
}

main() {
  banner
  local project_name=$1

  ###########################################################
  action "create project directory"
    mkdir -p $project_name
  ok

  ###########################################################
  action "initialize"
    ( cd $project_name && vagrant init ubuntu/trusty64; )
    # create gitignore
    gibo vagrant > $project_name/.gitignore
  ok

  action "Initialize EDITORCONFIG"
    cp $BOXROOTDIR/lib/editorconfig_template > $project_name/.editorconfig
  ok

}

# for examples of providing tab completion suggestions see:
# https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
# _cmd_vagrant() {
# }

cmd_vagrant() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_vagrant "$@"
