#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box android"
  echo
}

main() {
  banner
  get_platform
  bot "Install Android Development tools"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    action "Install Android Tools"
    require_brew android-platform-tools
    ok
    if [[ $1 != "--skip-gui" ]]; then
      action "Install Android Studio"
      require_cask android-studio
      ok
    fi
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
    action "Install Android Tools"
    sudo apt-get install -y android-tools-adb android-tools-fastboot
    ok
    if [[ $1 != "--skip-gui" ]]; then
      action "Install Android Studio"
      sudo apt-add-repository ppa:paolorotolo/android-studio
      sudo apt-get update
      sudo apt-get install -y android-studio
      ok
    fi
  fi
}

_cmd_android() {
  _values 'Params' \
    --skip-gui"[Skip installing the GUI applications]"
}

cmd_android() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_android "$@"
