#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box setup ansible"
  echo
}

main() {
  banner
  get_platform

  action "install python dependencies"
    sudo pip install --upgrade pip
    sudo pip install ansible
    ok

  action "install debops playbooks"
    sudo pip install ldap netaddr passlib debops
    sudo debops-update
    ok
}

# _cmd_ansible() {
# }

cmd_ansible() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_ansible "$@"
