#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box setup codeclimate"
  echo
}

main() {
  banner
  get_platform
  bot "Install Codeclimate"

  if [ "$NS_PLATFORM" == "darwin" ]; then
  	die 'implementation unfinished'

  	require_brew boot2docker
  	boot2docker init
  	boot2docker up
  	require_brew codeclimate

  # add lines to cli config
  	# export DOCKER_HOST=tcp://192.168.59.103:2376
  	# export DOCKER_CERT_PATH=/Users/rsherman/.boot2docker/certs/boot2docker-vm
  	# export DOCKER_TLS_VERIFY=1
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
  	die 'implementation unfinished'
  fi
}

# _cmd_codeclimate() {
# }

cmd_codeclimate() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_codeclimate "$@"
