#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box setup defaults"
  echo
}

main() {
  # echo "$@"
  banner
  get_platform
  bot "Setting System Defaults"
  source "$BOXROOTDIR/lib/defaults/_$NS_PLATFORM.sh"
}

# _cmd_defaults() {
# }

cmd_defaults() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_defaults "$@"
