#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box geektool"
  echo
}

main() {
  banner
  get_platform
  bot "Installing Geektool"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    require_cask geektool
    $BOXROOTDIR/lib/geektool/install.sh
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
    running "install conky"
    sudo apt-get install conky curl lm-sensors hddtemp
    ok

    running "copying config"
    cp $BOXROOTDIR/lib/conky/_conkyrc ~/.conkyrc
    ok

    action "adding conky to autostart"
    cp $BOXROOTDIR/lib/conky/conky.desktop ~/.config/autostart
    ok
  fi
}

# _cmd_geektool() {
# }

cmd_geektool() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_geektool "$@"
