#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box setup gitkraken"
  echo
}

main() {
  banner
  get_platform
  bot "RELEASE THE KRAKEN!!!"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    wget https://release.gitkraken.com/darwin/installGitKraken.dmg
    die 'Sorry-- you have to drive from here'
  fi
  if [ "$NS_PLATFORM" == "linux" ]; then
    wget https://release.gitkraken.com/linux/gitkraken-amd64.deb
    sudo dpkg --install gitkraken-amd64.deb
    rm -f gitkraken-amd64.deb
  fi
}

# _cmd_gitkraken() {
# }

cmd_gitkraken() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_gitkraken "$@"
