#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box setup gitshots"
  echo
}

main() {
  banner
  get_platform
  bot "Configuring GitShots"

  HOOKDIR="$HOME/.git_template"
  HOOKFILE="$HOOKDIR/hooks/post-commit"
  # shellcheck disable=SC2016
  HOOK='
  #!/usr/bin/env bash
  [ -d ~/.gitshots ] || mkdir -p ~/.gitshots
  FILE="~/.gitshots/$(date +%Y-%m-%d-%H%M%S).$(basename `pwd`).jpg"
  imagesnap -q -w 3 $FILE &
  '

  action "create git_template directory"
  mkdir -p "$HOOKDIR/hooks"
  action "write init.templatedir to global gitconfig"
  git config --global init.templatedir "$HOOKDIR"

  action "write post-commit hook"
  touch "$HOOKFILE"
  chmod +x "$HOOKFILE"
  echo "$HOOK" > "$HOOKFILE"
}

# _cmd_gitshots() {
# }

cmd_gitshots() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_gitshots "$@"
