#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box setup herokutoolbelt"
  echo
}

main() {
  banner
  get_platform
  bot "Installing Heroku Tools"

  if [ "$NS_PLATFORM" == "darwin" ]; then
  	require_cask heroku-toolbelt
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
  	wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  fi
}

# _cmd_herokutoolbelt() {
# }

cmd_herokutoolbelt() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_herokutoolbelt "$@"
