#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box setup mongodb"
  echo
}

main() {
  banner
  get_platform
  bot "Installing MongoDB"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    require_brew mongo

    running "setting mongodb to start automatically"
    ln -sfv /usr/local/opt/mongodb/*.plist ~/Library/LaunchAgents
    # launch mongodb now
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
    ok

    # a gui client for mongo
    if [[ $1 != "--skip-gui" ]]; then
      # require_cask mongohub
      require_cask robomongo
    fi
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
  	sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  	echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  	sudo apt-get update
  	sudo apt-get install -y mongodb-org

    if [[ $1 != "--skip-gui" ]]; then
      die "no UIAPP defined for linux"
    fi
  fi
}

_cmd_mongodb() {
  _values 'Params' \
    --skip-gui"[Skip installing the GUI applications]"
}

cmd_mongodb() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_mongodb "$@"
