#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box setup nodejs"
  echo
}

main() {
  echo "$@"
  banner

  get_platform

  bot "Installing NodeJS Development tools"

  # node version manager
  # allows per directory node versions with .nvmrc files
  git clone https://github.com/creationix/nvm.git ~/.nvm && cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`

  # nvm load in coderonin file
  profile_write "# initialize NVM" $HOME/.profile
  profile_write "export NVM_DIR=\$HOME/.nvm" $HOME/.profile
  profile_write '[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"' $HOME/.profile

  # immediately load nvm so we can install node and npm
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

  nvm install $1
  nvm alias default $1
  nvm alias system $1
}

_cmd_nodejs() {
  _alternative "version:NodeJS Version:(4.7.2 5.12.0 6.9.4 7.2.0)"
}

cmd_nodejs() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_nodejs "$@"
