#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box setup packer"
  echo
}

main() {
  banner
  get_platform
  bot "Install Hashicorp Packer"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    require_brew packer
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
    url=$(curl -s https://releases.hashicorp.com/index.json | jq '{packer}' | egrep "linux.*64" | sort -r | head -1 | awk -F[\"] '{print $4}')
    # Download Packer. URI: https://www.hashicorp.io/downloads.html
    curl -o hashicorp.zip $url && unzip hashicorp.zip -d ~/bin
    rm -rf hashicorp.zip
  fi
}

# _cmd_packer() {
# }

cmd_packer() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_hashicorp "$@"
