#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box php"
  echo
}

main() {
  banner
  get_platform
  bot "Installing PHP 7.0.1 Development tools"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    brew tap homebrew/dupes
    brew tap homebrew/versions
    brew tap homebrew/homebrew-php
    brew options php70
    require_brew php70
    brew link --overwrite php70
    ln -sfv /usr/local/opt/php70/*.plist ~/Library/LaunchAgents
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.php70.plist

    # edit /etc/apache2/httpd.conf
    # LoadModule php7_module /usr/local/Cellar/php70/7.0.1/libexec/apache2/libphp7.so
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
    die "not yet implemented"
  fi
}

# _cmd_php() {
#   _values 'Params' \
#     --skip-gui"[Skip installing the GUI applications]"
# }

cmd_php() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_php "$@"
