#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box setup postgres"
  echo
}

main() {
  banner
  get_platform
  bot "Installing Postgres"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    require_brew postgresql
    ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
    # initialize database
    initdb /usr/local/var/postgres
    # launch postgres now
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
    sudo apt-get install -y postgresql postgresql-contrib pgadmin3
  fi

  ok

  # install gui query browser
  if [[ "$1" != "--skip-gui" ]]; then
    source "${BOXROOTDIR}/functions/setup/valentina"
    cmd_valentina
  fi
}

_cmd_postgres() {
  _values 'Params' \
    --skip-gui"[Skip installing the GUI applications]"
}

cmd_postgres() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_postgres "$@"
