#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box setup redis"
  echo
}

main() {
  banner
  get_platform
  bot "Installing Redis"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    require_brew redis
    running "setting redis to start automatically"
    ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
    # Then to load redis now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
    ok
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
    sudo apt-add-repository ppa:chris-lea/redis-server
    sudo apt-get update
    sudo apt-get install -y redis-server
    # does it auto start ?
  fi

  # a gui client for redis
  if [[ $1 != "--skip-gui" ]]; then
    if [ "$NS_PLATFORM" == "darwin" ]; then
      require_cask rdm
    fi
    if [ "$NS_PLATFORM" == "linux" ]; then
      git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.8.0 rdm
      # shellcheck disable=SC1091
      ( cd ./rdm/src/ && ./configure && source /opt/qt56/bin/qt56-env.sh && qmake && make && sudo make install )
      ( cd /usr/share/redis-desktop-manager/bin && sudo mv qt.conf qt.backup )
    fi
  fi
}

_cmd_redis() {
  _values 'Params' \
    --skip-gui"[Skip installing the GUI applications]"
}

cmd_redis() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_redis "$@"
