#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box redis"
  echo
}

main() {
  banner
  get_platform
  bot "Installing Redis"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    require_brew redis

    running "setting redis to start automatically"
    ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
    # Then to load redis now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
    ok

    # a gui client for redis
    if [[ $1 != "--skip-gui" ]]; then
      require_cask rdm
    fi
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
    sudo apt-add-repository ppa:chris-lea/redis-server
    sudo apt-get update
    sudo apt-get install -y redis-server
    # does it auto start ?

    if [[ $1 != "--skip-gui" ]]; then
      die "no UIAPP defined for linux"
    fi
  fi
}

_cmd_redis() {
  _values 'Params' \
    --skip-gui"[Skip installing the GUI applications]"
}

cmd_redis() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_redis "$@"
