#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box setup sizeup"
  echo
}

main() {
  banner
  get_platform
  bot "Installing Sizeup Window Manager"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    # http://www.irradiatedsoftware.com/sizeup/
    require_cask sizeup

    running "Start SizeUp at login"
    defaults write com.irradiatedsoftware.SizeUp StartAtLogin -bool true;ok

    running "Don't show the preferences window on next start"
    defaults write com.irradiatedsoftware.SizeUp ShowPrefsOnNextStart -bool false;ok
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
  	die 'depending on your linux you already have a nice window manager..'
  fi
}

# _cmd_sizeup() {
# }

cmd_sizeup() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_sizeup "$@"
