#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box setup ssh"
  echo
}

main() {
  banner
  get_platform
  bot "SSH Setup"

  running "checking for existing rsa key"
  if [ ! -f ~/.ssh/id_rsa ]; then
    action "rsa key not present.. lets create one."

    if [ -z ${USER_EMAIL+x} ]; then
      prompt_email
    fi

    running "create rsa key"
      ssh-keygen -t rsa -b 2048 -C "$USER_EMAIL"
    ok

    # Then add your new key to the ssh-agent:
    # start the ssh-agent in the background
    running "start ssh-agent in the background"
      eval "$(ssh-agent -s)"
    ok

    running "adding yout key to the ssh-agent"
      ssh-add ~/.ssh/id_rsa
    ok
  else
    ok
  fi
}

# _cmd_ssh() {
# }

cmd_ssh() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_ssh "$@"
