#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box setup terraform"
  echo
}

main() {
  banner
  get_platform
  bot "Install Hashicorp Terraform"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    require_brew terraform
    require_brew terraform-inventory
    require_brew terraform-docs
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
    url=$(curl -s https://releases.hashicorp.com/index.json | jq '{terraform}' | grep "linux.*64" | sort -rh | head -1 | awk -F[\"] '{print $4}')
    # Download Terraform. URI: https://www.terraform.io/downloads.html
    curl -o terraform.zip "$url" && unzip terraform.zip -d ~/bin
    rm -rf terraform.zip

    url=$(curl -s https://api.github.com/repos/adammck/terraform-inventory/releases/latest | jq -r ".assets[]  | select(.name | test(\"linux_amd64\")) | .browser_download_url")
    # Download terraform-inventory. URI: https://github.com/adammck/terraform-inventory
    curl -o terraform-inventory.zip "$url" && unzip terraform-inventory.zip -d ~/bin
    rm -rf terraform-inventory.zip

    url=$(curl -s https://api.github.com/repos/segmentio/terraform-docs/releases/latest | jq -r ".assets[]  | select(.name | test(\"linux_amd64\")) | .browser_download_url")
    # Download terraform-docs. URI: https://github.com/segmentio/terraform-docs
    curl -o  ~/bin/terraform-docs "$url"
  fi
}

# _cmd_terraform() {
# }

cmd_terraform() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi

    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_terraform "$@"
