#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box setup thefuck"
  echo
}

main() {
  banner

  get_platform

  bot "Installing The Fuck"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    brew install thefuck
  fi
  if [ "$NS_PLATFORM" == "linux" ]; then
    sudo apt-get install python-pip python-dev
    sudo pip install psutil thefuck
  fi

  running "adding the fucking alias"
    profile_write "# initialize thefuck" $HOME/.profile
    profile_write 'eval "$(thefuck --alias)"' $HOME/.profile
    source $HOME/.profile
  ok
}

# _cmd_thefuck() {
# }

cmd_thefuck() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_thefuck "$@"
