#!/usr/bin/env bash

# shellcheck disable=SC1090
source "${BOXROOTDIR}/dotfiles/.lib_sh/functions.sh"

usage() {
  echo "usage: box setup vim"
  echo
}

main() {
  banner
  get_platform
  bot "Installing Valentina Studio"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    require_cask valentina-studio
  fi
  if [ "$NS_PLATFORM" == "linux" ]; then
    wget -O vstudio_x64_lin.deb http://www.valentina-db.com/en/studio/download/current/vstudio_x64_lin-deb?format=raw
    sudo dpkg --install vstudio_x64_lin.deb
    rm -f vstudio_x64_lin.deb
  fi
  ok
}

# _cmd_valentina() {
# }

cmd_valentina() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    main; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ "$1" == "help" ]]; then
      usage; exit 0
    fi
    main "$1"; exit 0
  fi

  usage; exit 1
}

# cmd_valentina "$@"
