#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box vim"
  echo
}

main() {
  banner
  get_platform
  bot "Installing Vim & Tmux"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    # install vim overriding system installed vim
    require_brew macvim --override-system-vim
    require_brew tmux
    require_brew reattach-to-user-namespace

    # add vundle to manage vim plugins
    git_clone_or_update https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

    # use vundle to install other plugins
    vim +PluginInstall +qall > /dev/null 2>&1
  fi

  if [ "$NS_PLATFORM" == "linux" ]; then
    die 'not implemented'
  fi
}

# _cmd_vim() {
# }

cmd_vim() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_vim "$@"
