#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box virtualbox"
  echo
}

main() {
  banner
  get_platform
  bot "Installing Virtualbox & Vagrant"

  running "Installing Virtualbox and Vagrant"
  if [ "$NS_PLATFORM" == "darwin" ]; then
    require_cask virtualbox
    require_cask vagrant
  fi
  if [ "$NS_PLATFORM" == "linux" ]; then
    sudo apt-get install -y virtualbox
    sudo apt-get install -y vagrant
  fi
  ok

  require_vagrant_plugin 'vagrant-proxmox'
  git clone https://github.com/telcat/vagrant-proxmox.git
  cd vagrant-proxmox
  vagrant box add dummy dummy_box/dummy.box
  cd ..
  rm -rf vagrant-proxmox
}

# _cmd_virtualbox() {
# }

cmd_virtualbox() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_virtualbox "$@"
