#!/usr/bin/env bash

source $BOXROOTDIR/dotfiles/.lib_sh/functions.sh

usage() {
  echo "usage: box vistudio"
  echo
}

main() {
  banner
  get_platform
  bot "Install Visual Studio Code Editor"

  if [ "$NS_PLATFORM" == "darwin" ]; then
    require_cask visual-studio-code
  fi
  if [ "$NS_PLATFORM" == "linux" ]; then
    wget -O code_1.7.2-1479766213_amd64.deb https://go.microsoft.com/fwlink/?LinkID=760868
    sudo dpkg --install code_1.7.2-1479766213_amd64.deb
    rm -f code_1.7.2-1479766213_amd64.deb
  fi
}

# _cmd_visualtudiocode() {
# }

cmd_visualtudiocode() {
  if [ "$#" -lt 1 ]; then # called with no parameters
    usage; exit 0

  elif [ "$#" -gt 1 ]; then # called with gt 1 parameters
    main "$@"; exit 0

  elif [ "$#" -eq 1 ]; then # called with 1 parameters
    if [[ $1 == "help" ]]; then
      usage; exit 0
    fi

    main $1; exit 0
  fi

  usage; exit 1
}

# cmd_visualtudiocode "$@"
